# rbac-pred-svc-reader.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pred-svc-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods","pods/log","configmaps","secrets"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pred-svc-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: pred-svc          # ← 必须跟 Deployment 里的 serviceAccountName 一致
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pred-svc-reader
