apiVersion: v1
kind: ServiceAccount
metadata:
  name: pred-svc
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pred-svc-jobrunner
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "pods/log"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pred-svc-jobrunner
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pred-svc
    namespace: default
roleRef:
  kind: Role
  name: pred-svc-jobrunner
  apiGroup: rbac.authorization.k8s.io
